/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

package org.apache.tsfile.viewer.service;

import static org.assertj.core.api.Assertions.assertThat;

import java.util.concurrent.CountDownLatch;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.concurrent.LinkedBlockingQueue;
import java.util.concurrent.Semaphore;
import java.util.concurrent.TimeUnit;
import java.util.concurrent.atomic.AtomicInteger;

import net.jqwik.api.*;

/**
 * Property-based tests for {@link ScanTaskExecutor} — concurrency control and queue behavior.
 *
 * <p>Verifies that the Semaphore-based concurrency control pattern used by the scan task executor
 * ensures at most 2 tasks run simultaneously, regardless of how many tasks are submitted
 * concurrently.
 *
 * <p>Validates: Requirements 3.1, 3.2
 */
class ScanTaskExecutorPropertyTest {

  /** Maximum number of concurrent tasks allowed, matching the design specification. */
  private static final int MAX_CONCURRENT = 2;

  /**
   * Property 6: 并发控制与队列行为
   *
   * <p>Simulates concurrent submission of multiple tasks using a {@link Semaphore} with {@code
   * MAX_CONCURRENT} permits and a {@link LinkedBlockingQueue}, mirroring the concurrency control
   * pattern in {@link ScanTaskExecutor}. Uses an {@link AtomicInteger} to track the number of
   * simultaneously running tasks and asserts that this count never exceeds {@code MAX_CONCURRENT}.
   *
   * <p>The number of submitted tasks is randomly generated by jqwik (between 3 and 10) to exercise
   * various concurrency scenarios.
   *
   * <p><b>Validates: Requirements 3.1, 3.2</b>
   */
  @Property(tries = 50)
  @Label("Feature: tsfile-scan, Property 6: 并发控制与队列行为")
  void concurrentRunningTasksShouldNeverExceedMaxConcurrent(@ForAll("taskCounts") int taskCount)
      throws InterruptedException {

    Semaphore semaphore = new Semaphore(MAX_CONCURRENT);
    LinkedBlockingQueue<Runnable> taskQueue = new LinkedBlockingQueue<>();
    AtomicInteger currentRunning = new AtomicInteger(0);
    AtomicInteger peakRunning = new AtomicInteger(0);
    CountDownLatch allTasksCompleted = new CountDownLatch(taskCount);

    ExecutorService executor = Executors.newFixedThreadPool(taskCount);

    try {
      // Submit all tasks concurrently
      for (int i = 0; i < taskCount; i++) {
        final int taskIndex = i;
        Runnable task =
            () -> {
              try {
                // Acquire semaphore permit before running (blocks if at capacity)
                semaphore.acquire();
                try {
                  // Track concurrent running count
                  int running = currentRunning.incrementAndGet();
                  // Update peak running count atomically
                  peakRunning.updateAndGet(peak -> Math.max(peak, running));

                  // Simulate task work with a brief sleep
                  Thread.sleep(10 + (taskIndex % 5) * 2);
                } finally {
                  currentRunning.decrementAndGet();
                  semaphore.release();
                }
              } catch (InterruptedException e) {
                Thread.currentThread().interrupt();
              } finally {
                allTasksCompleted.countDown();
              }
            };

        taskQueue.add(task);
        executor.submit(task);
      }

      // Wait for all tasks to complete (generous timeout)
      boolean completed = allTasksCompleted.await(30, TimeUnit.SECONDS);
      assertThat(completed)
          .as("All %d tasks should complete within the timeout", taskCount)
          .isTrue();

      // Verify: peak concurrent running tasks never exceeded MAX_CONCURRENT
      assertThat(peakRunning.get())
          .as(
              "Peak concurrent running tasks (%d) should not exceed MAX_CONCURRENT (%d)",
              peakRunning.get(), MAX_CONCURRENT)
          .isLessThanOrEqualTo(MAX_CONCURRENT);

      // Verify: all tasks were queued and executed
      assertThat(taskQueue).as("All tasks should have been queued").hasSize(taskCount);

      // Verify: no tasks are still running after completion
      assertThat(currentRunning.get())
          .as("No tasks should be running after all complete")
          .isEqualTo(0);

    } finally {
      executor.shutdownNow();
      executor.awaitTermination(5, TimeUnit.SECONDS);
    }
  }

  /**
   * Provides random task counts between 3 and 10 to exercise various concurrency scenarios where
   * the number of tasks exceeds the maximum concurrent limit.
   */
  @Provide
  Arbitrary<Integer> taskCounts() {
    return Arbitraries.integers().between(3, 10);
  }
}
